name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/mysql:8.0.33 docker://registry.cn-hangzhou.aliyuncs.com/wepay/mysql:8.0.33
        #  skopeo copy docker://docker.io/redis:6.2.12 docker://registry.cn-hangzhou.aliyuncs.com/wepay/redis:6.2.12
        #  skopeo copy docker://docker.io/minio/minio:RELEASE.2023-03-24T21-41-23Z docker://registry.cn-hangzhou.aliyuncs.com/wepay/minio:RELEASE.2023-03-24T21-41-23Z
        #  skopeo copy docker://docker.io/elasticsearch:7.17.6 docker://registry.cn-hangzhou.aliyuncs.com/wepay/elasticsearch:7.17.6
        #  skopeo copy docker://docker.io/logstash:7.17.6 docker://registry.cn-hangzhou.aliyuncs.com/wepay/logstash:7.17.6
        #  skopeo copy docker://docker.io/kibana:7.17.6 docker://registry.cn-hangzhou.aliyuncs.com/wepay/kibana:7.17.6
        #  skopeo copy docker://docker.io/apache/rocketmq:4.9.4 docker://registry.cn-hangzhou.aliyuncs.com/wepay/rocketmq:4.9.4
        #  skopeo copy docker://docker.io/styletang/rocketmq-console-ng docker://registry.cn-hangzhou.aliyuncs.com/wepay/rocketmq-console-ng
        #  skopeo copy docker://docker.io/rabbitmq:3.10.6 docker://registry.cn-hangzhou.aliyuncs.com/wepay/rabbitmq:3.10.6
        #  skopeo copy docker://docker.io/bitnami/zookeeper:3.8.0 docker://registry.cn-hangzhou.aliyuncs.com/wepay/zookeeper:3.8.0
        #  skopeo copy docker://docker.io/bitnami/kafka:3.2.0 docker://registry.cn-hangzhou.aliyuncs.com/wepay/kafka:3.2.0
        #  skopeo copy docker://docker.io/sheepkiller/kafka-manager:latest docker://registry.cn-hangzhou.aliyuncs.com/wepay/kafka-manager:latest
        #  skopeo copy docker://docker.io/bitnami/apache/skywalking-oap-server:9.3.0 docker://registry.cn-hangzhou.aliyuncs.com/wepay/skywalking-oap-server:9.3.0
        #  skopeo copy docker://docker.io/bitnami/apache/skywalking-ui:9.3.0 docker://registry.cn-hangzhou.aliyuncs.com/wepay/apache/skywalking-ui:9.3.0
        #  skopeo copy docker://docker.io/bitnami/prom/prometheus:v2.40.1 docker://registry.cn-hangzhou.aliyuncs.com/wepay/prometheus:v2.40.1
        #  skopeo copy docker://docker.io/bitnami/grafana/grafana:9.2.4 docker://registry.cn-hangzhou.aliyuncs.com/wepay/grafana:9.2.4
        #  skopeo copy docker://docker.io/bitnami/apache/shardingsphere-proxy:5.4.0 docker://registry.cn-hangzhou.aliyuncs.com/wepay/shardingsphere-proxy:5.4.0
         
         
